# Generated by Django 4.2.13 on 2024-07-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=120)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
